2025-10-13 19:40:38 | INFO | crm_logger | db_connection.py:17 | <module> | Connected to DB: 172.188.13.193:9832/dev-es
2025-10-13 19:49:44 | INFO | crm_logger | db_connection.py:17 | <module> | Connected to DB: 172.188.13.193:9832/dev-es
2025-10-13 19:49:44 | INFO | crm_logger | db_connection.py:17 | <module> | Connected to DB: 172.188.13.193:9832/dev-es
2025-10-13 19:58:46 | INFO | crm_logger | db_connection.py:17 | <module> | Connected to DB: 172.188.13.193:9832/dev-es
2025-10-13 19:58:46 | INFO | crm_logger | db_connection.py:17 | <module> | Connected to DB: 172.188.13.193:9832/dev-es
2025-10-13 19:58:46 | INFO | crm_logger | db_connection.py:17 | <module> | Connected to DB: 172.188.13.193:9832/dev-es
2025-10-13 20:00:42 | INFO | crm_logger | db_connection.py:17 | <module> | Connected to DB: 172.188.13.193:9832/dev-es
2025-10-13 20:00:42 | INFO | crm_logger | db_connection.py:17 | <module> | Connected to DB: 172.188.13.193:9832/dev-es
2025-10-13 20:00:42 | INFO | crm_logger | db_connection.py:17 | <module> | Connected to DB: 172.188.13.193:9832/dev-es
2025-10-13 20:00:42 | INFO | crm_logger | db_connection.py:17 | <module> | Connected to DB: 172.188.13.193:9832/dev-es
